language: python

services:
  - redis-server

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"

# command to install dependencies
install:
  - pip install .
  - pip install pyshould
  - pip install nose

# command to run tests
script: nosetests

notifications:
  email:
    - juan@pollinimini.net
